### ISSUE TITLE
Extension always shows gamemode is off, despite gamemoded -s saying it is on

### ISSUE THREAD

**Issue by Mastergatto** [gicmo/gamemode-extension#11]
Extension is installed via extensions.gnome.org, running Gnome-Shell 3.32 Wayland on Archlinux. Gamemode is installed through [AUR](https://aur.archlinux.org/packages/gamemode/).

**Comment by gicmo** [comment]
Which version of gamemode do you have installed? The extension needs at least 1.4, out only since Saturday.

**Comment by Mastergatto** [comment]
Yes, it's the 1.4 version.

**Comment by Mastergatto** [comment]
Somehow it now works correctly after turning on the computer, maybe a restart of some kind was needed to fix the issue. I apologize for wasting your time on such dumb mistake from me, I'm now closing this issue.

**Comment by gicmo** [comment]
No worries at all, glad it is resolved. Feel free to reopen if you encounter the bug again!
