### ISSUE TITLE
Small descrepency in meson.build file

### ISSUE THREAD

**Issue by highvoltage** [gicmo/gamemode-extension#13]
In the meson.build file, the version is stated as '0.1', but it seems the project version is actually '1'. Or is that just the version for the build script?

It also says "license: GPL2+' but the rest of the project is lgpl-2.1+.

Can you please clarify whether that's correct or whether it should be different?

thanks!

**Comment by gicmo** [comment]
Thanks for pointing that out. I changed the license to LGPL-2.1 to be in sync with what `LICENSE` actually says. The `meson.build` flag should say `4` in master.

**Comment by gicmo** [comment]
I think that is all fixed, thanks for the report!
