### ISSUE TITLE
does not work on ubuntu 18.04

### ISSUE THREAD

**Issue by zany130** [gicmo/gamemode-extension#19]
installing through gnome extensions gives an error and installing from the GitHub gives ./make-zip.sh install
The Meson build system
Version: 0.45.1
Source dir: /home/zany130/gamemode-extension
Build dir: /home/zany130/gamemode-extension/_build.Pi1bJy
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.45.1 but project requires >= 0.46.0.

A full log can be found at /home/zany130/gamemode-extension/_build.Pi1bJy/meson-logs/meson-log.txt

**Comment by cleveHEX** [comment]
Just use newer meson version
