### ISSUE TITLE
Add support for Gnome 3.36

### ISSUE THREAD

**Issue by AtifChy** [gicmo/gamemode-extension#20]
The title says everything.

**Comment by gicmo** [comment]
Will take care of it this weekend.

**Comment by terencode** [comment]
FYI some warnings to fix:

- Upon enabling
```
JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
                                                      notify@resource:///org/gnome/shell/ui/messageTray.js:870:23
                                                      _notify@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:212:26
                                                      _onStateChanged@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:259:26
                                                      _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                      _onProxyReady@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/client.js:81:18
```
- When locking/unlocking (meta+L) the screen: 
```
mars 21 00:37:46 terence-desktop gnome-shell[639003]: Object St.Icon (0x55636d906e50), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
mars 21 00:37:46 terence-desktop gnome-shell[639003]: == Stack trace for context 0x556369fc86c0 ==
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #0   55636d7925a8 i   /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:223 (fb8afbe5cb8 @ 172)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #1   7ffe96045a20 b   self-hosted:1003 (19ec490989e8 @ 423)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #2   7ffe96045b20 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #3   7ffe96046600 b   resource:///org/gnome/shell/ui/sessionMode.js:195 (19ec490233d0 @ 286)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #4   55636d792440 i   resource:///org/gnome/shell/ui/sessionMode.js:163 (19ec49023268 @ 116)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #5   55636d7923a8 i   resource:///org/gnome/shell/ui/screenShield.js:499 (19ec4900e268 @ 79)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #6   55636d792318 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e1f0 @ 17)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #7   55636d792280 i   resource:///org/gnome/shell/gdm/authPrompt.js:518 (19ec490318f8 @ 65)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #8   55636d7921e8 i   resource:///org/gnome/shell/ui/unlockDialog.js:844 (19ec490482e0 @ 40)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #9   55636d792158 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e178 @ 50)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #10   55636d7920c8 i   resource:///org/gnome/shell/ui/screenShield.js:109 (19ec4900c2e0 @ 13)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #11   7ffe96047150 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #12   55636d792018 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169 (3b350c9ce718 @ 39)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: == Stack trace for context 0x556369fc86c0 ==
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #0   55636d7925a8 i   /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:231 (fb8afbe5cb8 @ 331)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #1   7ffe96045a20 b   self-hosted:1003 (19ec490989e8 @ 423)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #2   7ffe96045b20 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #3   7ffe96046600 b   resource:///org/gnome/shell/ui/sessionMode.js:195 (19ec490233d0 @ 286)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #4   55636d792440 i   resource:///org/gnome/shell/ui/sessionMode.js:163 (19ec49023268 @ 116)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #5   55636d7923a8 i   resource:///org/gnome/shell/ui/screenShield.js:499 (19ec4900e268 @ 79)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #6   55636d792318 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e1f0 @ 17)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #7   55636d792280 i   resource:///org/gnome/shell/gdm/authPrompt.js:518 (19ec490318f8 @ 65)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #8   55636d7921e8 i   resource:///org/gnome/shell/ui/unlockDialog.js:844 (19ec490482e0 @ 40)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #9   55636d792158 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e178 @ 50)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #10   55636d7920c8 i   resource:///org/gnome/shell/ui/screenShield.js:109 (19ec4900c2e0 @ 13)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #11   7ffe96047150 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: #12   55636d792018 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169 (3b350c9ce718 @ 39)
mars 21 00:37:46 terence-desktop gnome-shell[639003]: clutter_actor_has_effects: assertion 'CLUTTER_IS_ACTOR (self)' failed
mars 21 00:37:46 terence-desktop gnome-shell[639003]: Object .Gjs_gamemode_christian_kellner_me_extension_GameModeIndicator (0x55636dbd7460), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
mars 21 00:37:46 terence-desktop gnome-shell[639003]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
                                                      notify@resource:///org/gnome/shell/ui/messageTray.js:870:23
                                                      _notify@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:212:26
                                                      _onStateChanged@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:259:26
                                                      _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                      _onProxyReady@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/client.js:81:18
```

**Comment by BloodyIron** [comment]
So when is this going to happen? I'm still getting these errors thrown constantly. And even still, why not update this to support newer gnome in general?

**Comment by gicmo** [comment]
Very sorry about that, mostly a total lack of time. I am very happy to review a patch.

**Comment by gicmo** [comment]
> FYI some warnings to fix:
> 
> * Upon enabling
> 
> ```
> JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
>                                                       notify@resource:///org/gnome/shell/ui/messageTray.js:870:23
>                                                       _notify@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:212:26
>                                                       _onStateChanged@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:259:26
>                                                       _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
>                                                       _onProxyReady@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/client.js:81:18
> ```
> 
> * When locking/unlocking (meta+L) the screen:
> 
> ```
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: Object St.Icon (0x55636d906e50), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: == Stack trace for context 0x556369fc86c0 ==
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #0   55636d7925a8 i   /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:223 (fb8afbe5cb8 @ 172)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #1   7ffe96045a20 b   self-hosted:1003 (19ec490989e8 @ 423)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #2   7ffe96045b20 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #3   7ffe96046600 b   resource:///org/gnome/shell/ui/sessionMode.js:195 (19ec490233d0 @ 286)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #4   55636d792440 i   resource:///org/gnome/shell/ui/sessionMode.js:163 (19ec49023268 @ 116)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #5   55636d7923a8 i   resource:///org/gnome/shell/ui/screenShield.js:499 (19ec4900e268 @ 79)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #6   55636d792318 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e1f0 @ 17)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #7   55636d792280 i   resource:///org/gnome/shell/gdm/authPrompt.js:518 (19ec490318f8 @ 65)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #8   55636d7921e8 i   resource:///org/gnome/shell/ui/unlockDialog.js:844 (19ec490482e0 @ 40)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #9   55636d792158 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e178 @ 50)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #10   55636d7920c8 i   resource:///org/gnome/shell/ui/screenShield.js:109 (19ec4900c2e0 @ 13)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #11   7ffe96047150 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #12   55636d792018 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169 (3b350c9ce718 @ 39)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: == Stack trace for context 0x556369fc86c0 ==
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #0   55636d7925a8 i   /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:231 (fb8afbe5cb8 @ 331)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #1   7ffe96045a20 b   self-hosted:1003 (19ec490989e8 @ 423)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #2   7ffe96045b20 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #3   7ffe96046600 b   resource:///org/gnome/shell/ui/sessionMode.js:195 (19ec490233d0 @ 286)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #4   55636d792440 i   resource:///org/gnome/shell/ui/sessionMode.js:163 (19ec49023268 @ 116)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #5   55636d7923a8 i   resource:///org/gnome/shell/ui/screenShield.js:499 (19ec4900e268 @ 79)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #6   55636d792318 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e1f0 @ 17)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #7   55636d792280 i   resource:///org/gnome/shell/gdm/authPrompt.js:518 (19ec490318f8 @ 65)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #8   55636d7921e8 i   resource:///org/gnome/shell/ui/unlockDialog.js:844 (19ec490482e0 @ 40)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #9   55636d792158 i   resource:///org/gnome/shell/ui/screenShield.js:490 (19ec4900e178 @ 50)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #10   55636d7920c8 i   resource:///org/gnome/shell/ui/screenShield.js:109 (19ec4900c2e0 @ 13)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #11   7ffe96047150 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (3b350c9c2358 @ 427)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: #12   55636d792018 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169 (3b350c9ce718 @ 39)
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: clutter_actor_has_effects: assertion 'CLUTTER_IS_ACTOR (self)' failed
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: Object .Gjs_gamemode_christian_kellner_me_extension_GameModeIndicator (0x55636dbd7460), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
> mars 21 00:37:46 terence-desktop gnome-shell[639003]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
>                                                       notify@resource:///org/gnome/shell/ui/messageTray.js:870:23
>                                                       _notify@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:212:26
>                                                       _onStateChanged@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/extension.js:259:26
>                                                       _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
>                                                       _onProxyReady@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/client.js:81:18
> ```

I think I have fixed this with release 5, which also adds support for 3.38 and 40.
