### ISSUE TITLE
Program `js60` not found on Ubuntu 20.04

### ISSUE THREAD

**Issue by Bakerbakura** [gicmo/gamemode-extension#25]
I tried installing the extension from source on Ubuntu 20.04 Focal Fossa, and it seemed to complete correctly, but checking the Extensions or Tweaks apps don't show this extension at all.
Looking more closely at the output during the install, I noticed that at one point in complained that the program `js60` was not found (I'll include the full output below). From some Googling it seems that this should be a part of the `libmozjs-60-dev` package, however on 20.04 the only available candidates are `libmozjs-52-dev` and `libmozjs-68-dev`.

Will this program install correctly if the program `js68` is used instead during install? I'm afraid I don't know JavaScript at all, so probably won't be any help in terms of making a pull request to fix this issue.

Also, how do I uninstall this not-quite-installed extension? Do I just delete the folder under `~/.local/share/gnome-shell/extensions`?

**Comment by gicmo** [comment]
I have bumped this to `js68` with release 5. Thanks for the bug report and sorry it took me so long to respond!
