### ISSUE TITLE
This extension now spams Gnome Logs.

### ISSUE THREAD

**Issue by Redbatman89** [gicmo/gamemode-extension#35]
I'm getting this error a lot. You need to update the extension to Gnome 3.38 please

Object .Gjs_gamemode_christian_kellner_me_extension_GameModeIndicator (0x5565b80a8c60), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

Object St.Icon (0x5565b7d04800), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://bugs.launchpad.net/bugs/1915023

**Comment by raffaelemancuso** [comment]
This is a bug in ubuntu docker: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1905519

**Comment by vanvugt** [comment]
> This is a bug in ubuntu docker: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1905519

No, this is https://bugs.launchpad.net/bugs/1915023. It doesn't look like https://bugs.launchpad.net/bugs/1905519

**Comment by gicmo** [comment]
I could reproduce this and I hope I have fixed this, see https://github.com/gicmo/gamemode-extension/pull/40#issuecomment-856881004
