### ISSUE TITLE
Fedora 34 - Gnome 40 - No property margin on GtkBox

### ISSUE THREAD

**Issue by HNGamingUK** [gicmo/gamemode-extension#45]
Hello,

I have recently downloaded version 5 and installed however it is not working for me. 

Fedora 34
GNOME 40.4

I installed the extension by completing the following:
1. Downloaded version 5 from https://extensions.gnome.org/extension/1852/gamemode/
2. Ran `sudo gnome-extensions install gamemodechristian.kellner.me.v5.shell-extension.zip --force` (No error messages)
3. Ran `sudo gnome-extensions enable gamemode@christian.kellner.me` (Error: `Failed to connect to GNOME Shell`)

I checked the gnome extension app but I am unable to enable it there either and a red warning symbol shows also
![image](https://user-images.githubusercontent.com/5269015/136586337-d604e52f-0d5d-4fc7-91cb-3b13f59f5b82.png)

Clicking the cog to edit settings shows the following error:
```
Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  make_row_switch@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:29:20
  _init@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:19:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:111:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I found a previous issue #37 which did mention about gtk4, I can confirm this is installed.

Hope this is enough information so far, if you require anymore do let me know.

**Comment by gicmo** [comment]
Keeping up with ever changing Shell is a pain. I will try to find some time or someone with more knowledge!

**Comment by fjsevilla-dev** [comment]
Hello, 

this is one of my top 10 extensions in every Gnome installation :).  I recently upgraded to version 41 and this is one of the 4 that sadly fail (thanks again Gnome XD).

Updating my own GTK APP (although written in Python) I've encountered the same error (GTK 4 has removed the `GtkBox.margin` property) so I've ventured to tinker a bit:

https://github.com/fjsevilla-dev/gamemode-extension

The extension works again without problems for me, **but I only tested it on Gnome-Shell 41.1 (GTK 4.4.1, GJS 1.70.0)**.

![gamemode](https://user-images.githubusercontent.com/69912056/141387395-f02a13f2-827e-4a4f-8136-11581a272ca9.png)

**Comment by gicmo** [comment]
@fjsevilla-dev neat! can you file a PR with that change, please?
