### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by fjsevilla-dev** [gicmo/gamemode-extension#49]
Hi,

the extension does not have a Spanish translation available, since there are only 13 small strings and I'm a native speaker, it isn't a lot of work and I would like to be able to help.

According to HACKING, translations are done by tx. I have contributed to the localisation of several projects before, but working directly with the GetText files (po, pot, mo). I haven't used transifex before and I don't know if anything else is required apart from submittng a request to join the translation team (done). 

THX

**Comment by gicmo** [comment]
I ack'ed your request! I think I have to pull them in before I make the release. I will probably put out a release soon, to fix the GTK 4 issue that _you_ fixed! ;)

**Comment by fjsevilla-dev** [comment]
Hi @gicmo, translation completed in TX and tested to see how it looks 🧐🤣
![gamemode_trans](https://user-images.githubusercontent.com/69912056/141707967-87c3e5cc-f9ec-40b4-8929-96467d44c53b.jpg)

Feel free to let me know if any problems with the translation or if anything else is needed to complete it.

**Comment by gicmo** [comment]
Pulled, commit and pushed. We should be good! Thanks!
