### ISSUE TITLE
Doesn't work on Fedora 35

### ISSUE THREAD

**Issue by bkdwt** [gicmo/gamemode-extension#50]
Hi. Fedora 35 comes with a version of gamemode extension doesn't work on Gnome 41. I have installed the development version but still not working.

![Screenshot from 2021-12-06 13-35-28](https://user-images.githubusercontent.com/51302074/144885141-d7bbf066-bc66-4e6c-9015-95e41d8e1585.png)

```
Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:47:50
  make_row_switch@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:29:20
  _init@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:19:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/gamemode@christian.kellner.me/prefs.js:111:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

```

**Comment by gicmo** [comment]
I need to make a new release and push it. Sorry.

**Comment by bkdwt** [comment]
> I need to make a new release and push it. Sorry.

Many thanks! :)

**Comment by ferdnyc** [comment]
@gicmo Sorry to pester you, but: Ping, on the new release?

**Comment by gicmo** [comment]
Release 6 is out, submitted an update to extensions.gnome.org (it is currently under review), and I did builds for Fedora 34+. I have tested it on F34 myself. I hope it works on F35 as well. Maybe @bkdwt can confirm (https://bodhi.fedoraproject.org/updates/FEDORA-2021-5353ccb8db).

**Comment by Chevek** [comment]
Tested on F35, works! Thank you!

**Comment by bkdwt** [comment]
> Release 6 is out, submitted an update to extensions.gnome.org (it is currently under review), and I did builds for Fedora 34+. I have tested it on F34 myself. I hope it works on F35 as well. Maybe @bkdwt can confirm (https://bodhi.fedoraproject.org/updates/FEDORA-2021-5353ccb8db).

Thanks so much! Working like a charm again. :D
