### ISSUE TITLE
Make a release for GNOME 43

### ISSUE THREAD

**Issue by kparal** [gicmo/gamemode-extension#59]
GNOME 43 is officially released, can you please create a new release of gamemode-extension and upload to extensions.gnome.org? Thanks!

**Comment by gicmo** [comment]
Released [v8](https://github.com/gicmo/gamemode-extension/releases/tag/v8)

**Comment by dacioromero** [comment]
Could you release the update on https://extensions.gnome.org/extension/1852/gamemode/?
