### ISSUE TITLE
Publish GNOME 43 version to extensions.gnome.org

### ISSUE THREAD

**Issue by kparal** [gicmo/gamemode-extension#62]
https://extensions.gnome.org/extension/1852/gamemode/ only supports GNOME 42 at the moment. Can you please publish version 8 for GNOME 43 compatibility on that website? Thanks @gicmo .

**Comment by andypiper** [comment]
Same now applies to 44

**Comment by dogo** [comment]
@gicmo Could you please publish the newer version to support Gnome 44 and 45?
