### ISSUE TITLE
Does not install on Ubuntu 19.04 

### ISSUE THREAD

**Issue by blastermaster77** [gicmo/gamemode-extension#8]
I get this error when trying to install. 

[The error](https://gist.github.com/blastermaster77/a0c8768a6d38dcbfcbe54d2c1f21143c)

**Comment by gicmo** [comment]
I guess I should document that, but you need `jq` installed when using `make-zip.sh`: `apt install jq` I believe.

**Comment by gicmo** [comment]
PR #10 adds checks for missing dependencies, like `jq`. That should help. If that doesn't fix your issue, please reopen.
